# Generated by Django 5.2.8 on 2025-11-28 08:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrecord',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='school',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='score',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='student_id',
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='auto_correct_score_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='class_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='school_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='school_operation_region',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='teacher_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='TrainingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('answer_value', models.CharField(blank=True, max_length=500, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main_app.trainingrecord')),
            ],
        ),
    ]
