# Generated by Django 5.2.8 on 2026-01-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_submitted_at_trainingrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='gender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='grade',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='user_role',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
